[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_src_filter = +<*> -<tests/TestDisplay.cpp>

; Tần số CPU 240MHz & Flash 80MHz
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L

; Cấu hình Flash 16MB & 8MB OPI PSRAM (Dành riêng cho N16R8)
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

; LittleFS & Partition Scheme
board_build.filesystem = littlefs
board_build.partitions = partitions_16mb.csv

; Build Flags: Dùng Hardware UART cho chip nạp CH343 (COM3)
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0

; Cổng nạp và tốc độ nạp qua chip CH343
upload_port = COM3
upload_speed = 460800

; Cấu hình Serial Monitor cho chip CH343 (COM3): Không kích hoạt DTR/RTS để không bị kẹt Bootloader
monitor_port = COM3
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

lib_deps = 
	adafruit/Adafruit GFX Library
	arkhipenko/TaskScheduler@^4.0.8
	bblanchon/ArduinoJson@^7.2.2
	adafruit/Adafruit SSD1306@^2.5.17
	adafruit/Adafruit ILI9341@^1.6.3
	adafruit/Adafruit ST7735 and ST7789 Library@^1.10.4
	bodmer/TJpg_Decoder@^1.1.0
	ricmoo/QRCode@^0.0.1